/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/models/Cleric.gltf -o src/components/Cleric.jsx -r public
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Cleric(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Cleric.gltf')
  const { actions } = useAnimations(animations, group)
  console.log("cleric",actions);
  setTimeout(()=>{
    actions["Spell1"].play({once:true})
    setInterval(() => {
      actions["Spell1"].stop();
    }, 2000);
  
  },6000)
  useEffect(()=>{
    actions["Idle"].reset().fadeIn(0.5).play();
    return ()=> actions["Idle"].fadeOut(0.5);

  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <skinnedMesh name="Cleric" geometry={nodes.Cleric.geometry} material={materials.Cleric_Texture} skeleton={nodes.Cleric.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Cleric.gltf')
