/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/models/Monk.gltf -o src/components/Monk.jsx -r public
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useEffect } from 'react'

export function Monk(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Monk.gltf')
  const { actions } = useAnimations(animations, group)
  console.log("monk",actions);
  setTimeout(()=>{
    actions["Attack"].play({once:true})
    setInterval(() => {
      actions["Attack"].stop();
    }, 2000);
  
  },4000)
  useEffect(()=>{
    actions["Idle"].reset().fadeIn(0.5).play();
    return ()=> actions["Idle"].fadeOut(0.5);

  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <skinnedMesh name="Monk" geometry={nodes.Monk.geometry} material={materials.Monk_Texture} skeleton={nodes.Monk.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Monk.gltf')
